---
- hosts: all
  become_user: root
  become: yes

  tasks:
  - name: logging into Docker Registry
    docker_login:
      registry: "{{ docker_registry_url }}"
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"
    when: docker_user != ""      
  