###
# /ssh enpoint - get xOpera's public key
###

# curl -X GET "http://localhost:8080/ssh/keys/public" -H  "accept: application/json"
GET http://localhost:8080/ssh/keys/public
accept: application/json

###
# /blueprint endpoint
###

### Upload new blueprint

# curl -X POST "http://localhost:8080/blueprint?revision_msg=First%20version&project_domain=my_project_domain" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "CSAR=@CSAR-test.zip;type=application/zip"
POST http://localhost:8080/blueprint?revision_msg=First%20version&project_domain=my_project_domain
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="CSAR"; filename="CSAR-test.zip"

< CSAR-test.zip
--WebAppBoundary--

### Upload another version of existing blueprint

# curl -X POST "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423?revision_msg=Upgraded%20version" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "CSAR=@CSAR-test.zip;type=application/zip"
POST http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423?revision_msg=Upgraded%20version
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="CSAR"; filename="CSAR-test.zip"

< CSAR-test.zip
--WebAppBoundary--

### delete entire blueprint

# curl -X DELETE "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423?force=false" -H  "accept: application/json" -H  "X-API-Key: test"
DELETE http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423?force=false
accept: application/json
X-API-Key: test

### delete a blueprint version

# curl -X DELETE "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/version/v2.0?force=false" -H  "accept: application/json" -H  "X-API-Key: test"
DELETE http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/version/v2.0?force=false
accept: application/json
X-API-Key: test

### get list of users with access to blueprint

# curl -X GET "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user" -H  "accept: application/json" -H  "X-API-Key: test"
GET http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user
accept: application/json
X-API-Key: test

### grant user an access to blueprint

# curl -X POST "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user/my_user" -H  "accept: application/json" -H  "X-API-Key: test" -d ""
POST http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user/my_user
accept: application/json
X-API-Key: test
Content-Type: application/x-www-form-urlencoded

### remove blueprint access from user

# curl -X DELETE "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user/my_user" -H  "accept: application/json" -H  "X-API-Key: test"
DELETE http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/user/my_user
accept: application/json
X-API-Key: test

### validate last version of existing blueprint

# curl -X PUT "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/validate" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/validate
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### validate specific version of existing blueprint

# curl -X PUT "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/version/v1.0/validate" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/version/v1.0/validate
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### validate new blueprint

# curl -X PUT "http://localhost:8080/blueprint/validate" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "CSAR=@CSAR-test.zip;type=application/zip" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/blueprint/validate
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="CSAR"; filename="CSAR-test.zip"

< CSAR-test.zip
--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### retrieve history of transactions (update, delete) to repository with blueprint

# curl -X GET "http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/git_history" -H  "accept: application/json" -H  "X-API-Key: test"
GET http://localhost:8080/blueprint/854cc717-fd02-4c51-a35d-7223f9fc8423/git_history
accept: application/json
X-API-Key: test

###
# /deployment endpoint
###

### check if blueprint version (with inputs) is already a part of existing deployment

# curl -X PUT "http://localhost:8080/deployment/exists?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/exists?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### Initialize deployment and deploy

# curl -X POST "http://localhost:8080/deployment/deploy?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v2.0&workers=10" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/deploy?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v2.0&workers=10
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### Check deployment status (last invocation)

# curl -X GET "http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/status" -H  "accept: application/json" -H  "X-API-Key: test"
GET http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/status
accept: application/json
X-API-Key: test

### Check deployment history (list of all invocations)

# curl -X GET "http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/history" -H  "accept: application/json" -H  "X-API-Key: test"
GET http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/history
accept: application/json
X-API-Key: test

### Continue deployment, possibly from clean-state

# curl -X POST "http://localhost:8080/deployment/854cc717-fd02-4c51-a35d-7223f9fc8423/deploy_continue?workers=10&clean_state=false" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/854cc717-fd02-4c51-a35d-7223f9fc8423/deploy_continue?workers=10&clean_state=false
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### Calculate diff between current deployment and new blueprint version (with inputs)

# curl -X PUT "http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/diff?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/diff?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### Update deployment with new blueprint

# curl -X POST "http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/update?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0&workers=10" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/update?blueprint_id=854cc717-fd02-4c51-a35d-7223f9fc8423&version_id=v1.0&workers=10
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

### Undeploy deployment

# curl -X POST "http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/undeploy?workers=10" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@inputs.yaml;type=application/x-yaml"
POST http://localhost:8080/deployment/4a7b9983-dc27-4e43-b7b3-8b696a550fac/undeploy?workers=10
accept: application/json
X-API-Key: test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="inputs.yaml"

< inputs.yaml
--WebAppBoundary--

###

