roles:
  # Install a roles from Ansible Galaxy.
  - src: geerlingguy.docker
    version: 3.0.0
  - src: geerlingguy.pip
    version: 2.0.0
  - src: geerlingguy.repo-epel
    version: 3.0.0



collections:
  - name: community.kubernetes
    version: 1.2.0
  - name: openstack.cloud
    version: 1.3.0