### examples assume, REST_API runs on localhost:5000, if that is not the case, change accordingly.

############ SWAGGER DOCS ################

# just visit http://localhost:5000/ with your browser


################ FIRST RUN ######################
# GET REST api's ssh public key

# curl -X "GET" localhost:5000/ssh/keys/public
GET localhost:5000/ssh/keys/public
Content-Type: application/x-www-form-urlencoded

###

################ DEPLOY ##########################
# NOTES: - you can upload new blueprint or just another version of existing blueprint
#        - save blueprint metadata from response, blueprints can only be accessed via blueprint_token (optionally in combination with version_id or timestamp)

# 1a) upload new blueprint
# curl -H "Content-Type: application/json" -X "POST" --data-binary @blueprint.json localhost:5000/manage
POST localhost:5000/manage
Content-Type: application/json

< blueprint.json

###

# 1b) upload new version of existing blueprint (multiple versions can be stored and accessed later)
# change 567858fc-a1e8-43b4-91f5-cb04ec8be90b with token of your blueprint
# curl -H "Content-Type: application/json" -X "POST" --data-binary @blueprint.json localhost:5000/manage/b3a7123e-f996-4561-b621-de1877f680ae
POST localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/json

< blueprint.json

###

# 2a) deploy last version of blueprint
# curl -X "POST" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
POST localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/x-www-form-urlencoded

###

# 2b) deploy version of blueprint, referenced by version_id
# curl -X "POST" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=2
POST localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=2
Content-Type: application/x-www-form-urlencoded

###

# 2c) deploy version of blueprint, referenced by timestamp
# curl -X "POST" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-12-23T12:19:47.353823
POST localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-12-23T12:19:47.353823
Content-Type: application/x-www-form-urlencoded

###

# 2d deploy with inputs
# name must be set to inputs_file
# curl -X "POST" -F "inputs_file=@path/to/file.yaml" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
POST localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="file.yaml"

< path/to/file.yaml
--WebAppBoundary--

###


# 3) check status of deploy job (change b3a7123e-f996-4561-b621-de1877f680ae with your session_token)
# curl -X "GET" localhost:5000/info/status?token=b3a7123e-f996-4561-b621-de1877f680ae
GET localhost:5000/info/status?token=b3a7123e-f996-4561-b621-de1877f680ae
Content-Type: application/x-www-form-urlencoded

###

# 4) after completion, check logs
# 4a) check logs for given session
# curl -X "GET" localhost:5000/info/log?session_token=b3a7123e-f996-4561-b621-de1877f680ae
GET localhost:5000/info/log?session_token=b3a7123e-f996-4561-b621-de1877f680ae
Content-Type: application/x-www-form-urlencoded

###

# 4b) check log of all sessions with given blueprint
# curl -X "GET" localhost:5000/info/log?blueprint_token=567858fc-a1e8-43b4-91f5-cb04ec8be90b
GET localhost:5000/info/log?blueprint_token=567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/x-www-form-urlencoded

###

################ UNDEPLOY ##########################
# NOTES: - deployment can be undeployed with same blueprint, used for deployin

# 1a) undeploy last version of blueprint
# curl -X "DELETE" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
DELETE localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/x-www-form-urlencoded

###

# 1b) undeploy version of blueprint, referenced by version_id
# curl -X "DELETE" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=2
DELETE localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=2
Content-Type: application/x-www-form-urlencoded

###

# 1c) undeploy version of blueprint, referenced by timestamp
# curl -X "DELETE" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-12-23T12:19:47.353823
DELETE localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-12-23T12:19:47.353823
Content-Type: application/x-www-form-urlencoded

###

# 1d) undeploy with inputs
# name must be set to inputs_file
# curl -X "DELETE" -F "inputs_file=@path/to/file.yaml" localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
DELETE localhost:5000/deploy/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="inputs_file"; filename="file.yaml"

< path/to/file.yaml
--WebAppBoundary--

###



# 2) check status of deploy job (change b3a7123e-f996-4561-b621-de1877f680ae with your session_token)
# curl -X "GET" localhost:5000/info/status?token=b3a7123e-f996-4561-b621-de1877f680ae
GET localhost:5000/info/status?token=b3a7123e-f996-4561-b621-de1877f680ae
Content-Type: application/x-www-form-urlencoded

###

# 3) after completion, check logs
# 3a) check logs for given session
# curl -X "GET" localhost:5000/info/log?session_token=b3a7123e-f996-4561-b621-de1877f680ae
GET localhost:5000/info/log?session_token=b3a7123e-f996-4561-b621-de1877f680ae
Content-Type: application/x-www-form-urlencoded

###

# 3b) check log of all sessions with given blueprint
# curl -X "GET" localhost:5000/info/log?blueprint_token=567858fc-a1e8-43b4-91f5-cb04ec8be90b
GET localhost:5000/info/log?blueprint_token=567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/x-www-form-urlencoded

###

# 4) after undeploying, (optionally) delete blueprint from REST API's database
# NOTES - REST API will not allow deleting of blueprint, deployment from which has not been undeployed yet.
#       - this failsafe can be overrided with query parameter 'force' set to True

# 4a) delete all versions of blueprint
# curl -X "DELETE" localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b
DELETE localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b
Content-Type: application/x-www-form-urlencoded

###

# 4b) delete version of blueprint, referenced by version_id
# curl -X "DELETE" localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=3
DELETE localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?version_id=3
Content-Type: application/x-www-form-urlencoded

###

# 4c) delete version of blueprint, referenced by timestamp
# curl -X "DELETE" localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-05-22T12:38:47.335823
DELETE localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?timestamp=2019-05-22T12:38:47.335823
Content-Type: application/x-www-form-urlencoded

###

# 4d) delete all versions with force (works with 4b) and 4c) as well
# curl -X "DELETE" localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?force=True
DELETE localhost:5000/manage/567858fc-a1e8-43b4-91f5-cb04ec8be90b?force=True
Content-Type: application/x-www-form-urlencoded

###