tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - docker_component.yaml

node_types:

  sodalite.nodes.DockerHost:  
    derived_from: tosca.nodes.SoftwareComponent 
    capabilities:  
      host:  
        type: tosca.capabilities.Node 
        valid_source_types: ['sodalite.nodes.DockerizedComponent'] 
    interfaces:  
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard 
        operations:
          create:  
            implementation:  
              primary: playbooks/create_docker_host.yml   
          delete:  
            implementation:  
              primary: playbooks/delete_docker_host.yml 
       
       
                 

