- hosts: all
  become_user: root
  become: yes

  tasks:
    - set_fact:
        env_dest: "{{ dir }}/{{ file_name }}"
    - name: Make dir if it does not exist
      file:
        path: "{{ dir }}"
        state: directory

    - name: Copy env_file
      copy:
        content: "\nXOPERA_GIT_TYPE={{ git_type }}
                  \nXOPERA_GIT_URL={{ git_url }}
                  \nXOPERA_GIT_AUTH_TOKEN={{ git_auth_token }}
                  \nXOPERA_VERBOSE_MODE={{ verbose_mode }}
                  \nXOPERA_DATABASE_IP={{ database_ip }}
                  \nXOPERA_DATABASE_NAME={{ database_name }}
                  \nXOPERA_DATABASE_USER={{ database_user }}
                  \nXOPERA_DATABASE_PASSWORD={{ database_password }}\n"
        dest: "{{ env_dest }}"

    - name: Set attributes
      set_stats:
        data:
          env_file:  "{{ env_dest }}"