name: Build

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r REST_API/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest REST_API/Implementation/tests
      env:
        XOPERA_TESTING: True
